### ISSUE TITLE
Does not seem to detect a non supported URL

### ISSUE THREAD

**Issue by cncook001** [bdadam/video-url-inspector#10]
This seems to be ok:

var video = inspect('https://www.google.com/watch?v=kl1LY8obJWs');

I would expect some sort of error to be returned.

**Comment by bdadam** [comment]
Thanks, this seems to be a bug in the regex used for checking Youtube urls. I will try to fix it.

**Comment by bdadam** [comment]
Must be fixed now. See https://github.com/bdadam/video-url-inspector/commit/7eeba16dad30ce2f1a84a43bcd85d94df410383b

**Comment by bdadam** [comment]
Must be fixed now.
