### ISSUE TITLE
Update & publish

### ISSUE THREAD

**Issue by JSteunou** [bdadam/video-url-inspector#4]
Please add old tag 1.0.0 on 6e99239, publish a 1.0.1 with all last fixes and publish on npm

`npm install video-url-inspector` currently install an old 1.0.0 release and I would like to have last fixes :)

**Comment by JSteunou** [comment]
@bdadam any chance?

**Comment by tteltrab** [comment]
:+1:, need the fix for #5 (I think #2 actually fixes this?).

**Comment by bdadam** [comment]
Thanks and sorry for the slow response. I bumped the version number in npm. It should be fine again.

**Comment by JSteunou** [comment]
Thank you @bdadam later is better than never ;)
