### ISSUE TITLE
dailymotion inspection returns vimeo urls

### ISSUE THREAD

**Issue by gebharra** [bdadam/video-url-inspector#5]
var inspect = require("video-url-inspector");
inspect("https://www.dailymotion.com/video/x1ndpyi_what-will-you-do-with-ibm-watson_tech");

> { hoster: 'dailymotion',
> remoteId: 'NaN',
> canonicalUrl: 'http://vimeo.com/NaN',
> embedUrl: 'http://player.vimeo.com/video/NaN' }

**Comment by bdadam** [comment]
Thanks for creating this issue. I bumped the version number in npm. It should be fine again.
