### ISSUE TITLE
Dailymotion support missing tiny url and query param "start"

### ISSUE THREAD

**Issue by JSteunou** [bdadam/video-url-inspector#6]
- dailymotion has short / tiny url service on `dai.ly`
- dailymotion shared urls can have query param `start`

**Comment by bdadam** [comment]
Thanks for the addition.

**Comment by JSteunou** [comment]
no problem. Could you bump package.json version and npm pub please, I would love to use that version ;)

**Comment by bdadam** [comment]
Sorry, it took a few days, but now the new version should be available on npm.
